on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Debug Secrets (non-sensitive)
        run: |
          echo "EC2_HOST is $EC2_HOST"
          echo "EC2_USER is $EC2_USER"
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}

      - name: Add SSH Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          # Ensure private key is securely written and set correct permissions
          echo "$PRIVATE_KEY" > todo.pem
          chmod 600 todo.pem

          # Test SSH Connection
          ssh -o StrictHostKeyChecking=no -i todo.pem $EC2_USER@$EC2_HOST "echo 'SSH Key Test Passed'"

          # Transfer application files to EC2 instance
          scp -o StrictHostKeyChecking=no -i todo.pem -r ./* $EC2_USER@$EC2_HOST:/home/$EC2_USER/app

          # SSH into EC2 instance and deploy the app
          ssh -o StrictHostKeyChecking=no -i todo.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Navigate to the application directory
            cd /home/$EC2_USER/app
            
            # Install dependencies on the EC2 instance
            npm install
            
            # Stop any running PM2 processes (if any)
            pm2 stop all || true
            
            # Start the server using PM2
            pm2 start server.js
          EOF
